export interface Country {
    code: string;
    dialCode: string;
    flag: string;
    name: string;
}

export const COUNTRIES: Country[] = [
    { code: 'AF', dialCode: '+93', flag: '🇦🇫', name: 'Afghanistan' },
    { code: 'AL', dialCode: '+355', flag: '🇦🇱', name: 'Albania' },
    { code: 'DZ', dialCode: '+213', flag: '🇩🇿', name: 'Algeria' },
    { code: 'AS', dialCode: '+1684', flag: '🇦🇸', name: 'American Samoa' },
    { code: 'AD', dialCode: '+376', flag: '🇦🇩', name: 'Andorra' },
    { code: 'AO', dialCode: '+244', flag: '🇦🇴', name: 'Angola' },
    { code: 'AI', dialCode: '+1264', flag: '🇦🇮', name: 'Anguilla' },
    { code: 'AQ', dialCode: '+672', flag: '🇦🇶', name: 'Antarctica' },
    { code: 'AG', dialCode: '+1268', flag: '🇦🇬', name: 'Antigua and Barbuda' },
    { code: 'AR', dialCode: '+54', flag: '🇦🇷', name: 'Argentina' },
    { code: 'AM', dialCode: '+374', flag: '🇦🇲', name: 'Armenia' },
    { code: 'AW', dialCode: '+297', flag: '🇦🇼', name: 'Aruba' },
    { code: 'AU', dialCode: '+61', flag: '🇦🇺', name: 'Australia' },
    { code: 'AT', dialCode: '+43', flag: '🇦🇹', name: 'Austria' },
    { code: 'AZ', dialCode: '+994', flag: '🇦🇿', name: 'Azerbaijan' },
    { code: 'BS', dialCode: '+1242', flag: '🇧🇸', name: 'Bahamas' },
    { code: 'BH', dialCode: '+973', flag: '🇧🇭', name: 'Bahrain' },
    { code: 'BD', dialCode: '+880', flag: '🇧🇩', name: 'Bangladesh' },
    { code: 'BB', dialCode: '+1246', flag: '🇧🇧', name: 'Barbados' },
    { code: 'BY', dialCode: '+375', flag: '🇧🇾', name: 'Belarus' },
    { code: 'BE', dialCode: '+32', flag: '🇧🇪', name: 'Belgium' },
    { code: 'BZ', dialCode: '+501', flag: '🇧🇿', name: 'Belize' },
    { code: 'BJ', dialCode: '+229', flag: '🇧🇯', name: 'Benin' },
    { code: 'BM', dialCode: '+1441', flag: '🇧🇲', name: 'Bermuda' },
    { code: 'BT', dialCode: '+975', flag: '🇧🇹', name: 'Bhutan' },
    { code: 'BO', dialCode: '+591', flag: '🇧🇴', name: 'Bolivia' },
    { code: 'BA', dialCode: '+387', flag: '🇧🇦', name: 'Bosnia and Herzegovina' },
    { code: 'BW', dialCode: '+267', flag: '🇧🇼', name: 'Botswana' },
    { code: 'BR', dialCode: '+55', flag: '🇧🇷', name: 'Brazil' },
    { code: 'IO', dialCode: '+246', flag: '🇮🇴', name: 'British Indian Ocean Territory' },
    { code: 'VG', dialCode: '+1284', flag: '🇻🇬', name: 'British Virgin Islands' },
    { code: 'BN', dialCode: '+673', flag: '🇧🇳', name: 'Brunei' },
    { code: 'BG', dialCode: '+359', flag: '🇧🇬', name: 'Bulgaria' },
    { code: 'BF', dialCode: '+226', flag: '🇧🇫', name: 'Burkina Faso' },
    { code: 'BI', dialCode: '+257', flag: '🇧🇮', name: 'Burundi' },
    { code: 'KH', dialCode: '+855', flag: '🇰🇭', name: 'Cambodia' },
    { code: 'CM', dialCode: '+237', flag: '🇨🇲', name: 'Cameroon' },
    { code: 'CA', dialCode: '+1', flag: '🇨🇦', name: 'Canada' },
    { code: 'CV', dialCode: '+238', flag: '🇨🇻', name: 'Cape Verde' },
    { code: 'KY', dialCode: '+1345', flag: '🇰🇾', name: 'Cayman Islands' },
    { code: 'CF', dialCode: '+236', flag: '🇨🇫', name: 'Central African Republic' },
    { code: 'TD', dialCode: '+235', flag: '🇹🇩', name: 'Chad' },
    { code: 'CL', dialCode: '+56', flag: '🇨🇱', name: 'Chile' },
    { code: 'CN', dialCode: '+86', flag: '🇨🇳', name: 'China' },
    { code: 'CX', dialCode: '+61', flag: '🇨🇽', name: 'Christmas Island' },
    { code: 'CC', dialCode: '+61', flag: '🇨🇨', name: 'Cocos (Keeling) Islands' },
    { code: 'CO', dialCode: '+57', flag: '🇨🇴', name: 'Colombia' },
    { code: 'KM', dialCode: '+269', flag: '🇰🇲', name: 'Comoros' },
    { code: 'CK', dialCode: '+682', flag: '🇨🇰', name: 'Cook Islands' },
    { code: 'CR', dialCode: '+506', flag: '🇨🇷', name: 'Costa Rica' },
    { code: 'HR', dialCode: '+385', flag: '🇭🇷', name: 'Croatia' },
    { code: 'CU', dialCode: '+53', flag: '🇨🇺', name: 'Cuba' },
    { code: 'CW', dialCode: '+599', flag: '🇨🇼', name: 'Curaçao' },
    { code: 'CY', dialCode: '+357', flag: '🇨🇾', name: 'Cyprus' },
    { code: 'CZ', dialCode: '+420', flag: '🇨🇿', name: 'Czech Republic' },
    { code: 'CD', dialCode: '+243', flag: '🇨🇩', name: 'Democratic Republic of the Congo' },
    { code: 'DK', dialCode: '+45', flag: '🇩🇰', name: 'Denmark' },
    { code: 'DJ', dialCode: '+253', flag: '🇩🇯', name: 'Djibouti' },
    { code: 'DM', dialCode: '+1767', flag: '🇩🇲', name: 'Dominica' },
    { code: 'DO', dialCode: '+1809', flag: '🇩🇴', name: 'Dominican Republic' },
    { code: 'TL', dialCode: '+670', flag: '🇹🇱', name: 'East Timor' },
    { code: 'EC', dialCode: '+593', flag: '🇪🇨', name: 'Ecuador' },
    { code: 'EG', dialCode: '+20', flag: '🇪🇬', name: 'Egypt' },
    { code: 'SV', dialCode: '+503', flag: '🇸🇻', name: 'El Salvador' },
    { code: 'GQ', dialCode: '+240', flag: '🇬🇶', name: 'Equatorial Guinea' },
    { code: 'ER', dialCode: '+291', flag: '🇪🇷', name: 'Eritrea' },
    { code: 'EE', dialCode: '+372', flag: '🇪🇪', name: 'Estonia' },
    { code: 'ET', dialCode: '+251', flag: '🇪🇹', name: 'Ethiopia' },
    { code: 'FK', dialCode: '+500', flag: '🇫🇰', name: 'Falkland Islands' },
    { code: 'FO', dialCode: '+298', flag: '🇫🇴', name: 'Faroe Islands' },
    { code: 'FJ', dialCode: '+679', flag: '🇫🇯', name: 'Fiji' },
    { code: 'FI', dialCode: '+358', flag: '🇫🇮', name: 'Finland' },
    { code: 'FR', dialCode: '+33', flag: '🇫🇷', name: 'France' },
    { code: 'PF', dialCode: '+689', flag: '🇵🇫', name: 'French Polynesia' },
    { code: 'GA', dialCode: '+241', flag: '🇬🇦', name: 'Gabon' },
    { code: 'GM', dialCode: '+220', flag: '🇬🇲', name: 'Gambia' },
    { code: 'GE', dialCode: '+995', flag: '🇬🇪', name: 'Georgia' },
    { code: 'DE', dialCode: '+49', flag: '🇩🇪', name: 'Germany' },
    { code: 'GH', dialCode: '+233', flag: '🇬🇭', name: 'Ghana' },
    { code: 'GI', dialCode: '+350', flag: '🇬🇮', name: 'Gibraltar' },
    { code: 'GR', dialCode: '+30', flag: '🇬🇷', name: 'Greece' },
    { code: 'GL', dialCode: '+299', flag: '🇬🇱', name: 'Greenland' },
    { code: 'GD', dialCode: '+1473', flag: '🇬🇩', name: 'Grenada' },
    { code: 'GU', dialCode: '+1671', flag: '🇬🇺', name: 'Guam' },
    { code: 'GT', dialCode: '+502', flag: '🇬🇹', name: 'Guatemala' },
    { code: 'GG', dialCode: '+44', flag: '🇬🇬', name: 'Guernsey' },
    { code: 'GN', dialCode: '+224', flag: '🇬🇳', name: 'Guinea' },
    { code: 'GW', dialCode: '+245', flag: '🇬🇼', name: 'Guinea-Bissau' },
    { code: 'GY', dialCode: '+592', flag: '🇬🇾', name: 'Guyana' },
    { code: 'HT', dialCode: '+509', flag: '🇭🇹', name: 'Haiti' },
    { code: 'HN', dialCode: '+504', flag: '🇭🇳', name: 'Honduras' },
    { code: 'HK', dialCode: '+852', flag: '🇭🇰', name: 'Hong Kong' },
    { code: 'HU', dialCode: '+36', flag: '🇭🇺', name: 'Hungary' },
    { code: 'IS', dialCode: '+354', flag: '🇮🇸', name: 'Iceland' },
    { code: 'IN', dialCode: '+91', flag: '🇮🇳', name: 'India' },
    { code: 'ID', dialCode: '+62', flag: '🇮🇩', name: 'Indonesia' },
    { code: 'IR', dialCode: '+98', flag: '🇮🇷', name: 'Iran' },
    { code: 'IQ', dialCode: '+964', flag: '🇮🇶', name: 'Iraq' },
    { code: 'IE', dialCode: '+353', flag: '🇮🇪', name: 'Ireland' },
    { code: 'IM', dialCode: '+44', flag: '🇮🇲', name: 'Isle of Man' },
    { code: 'IL', dialCode: '+972', flag: '🇮🇱', name: 'Israel' },
    { code: 'IT', dialCode: '+39', flag: '🇮🇹', name: 'Italy' },
    { code: 'CI', dialCode: '+225', flag: '🇨🇮', name: 'Ivory Coast' },
    { code: 'JM', dialCode: '+1876', flag: '🇯🇲', name: 'Jamaica' },
    { code: 'JP', dialCode: '+81', flag: '🇯🇵', name: 'Japan' },
    { code: 'JE', dialCode: '+44', flag: '🇯🇪', name: 'Jersey' },
    { code: 'JO', dialCode: '+962', flag: '🇯🇴', name: 'Jordan' },
    { code: 'KZ', dialCode: '+7', flag: '🇰🇿', name: 'Kazakhstan' },
    { code: 'KE', dialCode: '+254', flag: '🇰🇪', name: 'Kenya' },
    { code: 'KI', dialCode: '+686', flag: '🇰🇮', name: 'Kiribati' },
    { code: 'XK', dialCode: '+383', flag: '🇽🇰', name: 'Kosovo' },
    { code: 'KW', dialCode: '+965', flag: '🇰🇼', name: 'Kuwait' },
    { code: 'KG', dialCode: '+996', flag: '🇰🇬', name: 'Kyrgyzstan' },
    { code: 'LA', dialCode: '+856', flag: '🇱🇦', name: 'Laos' },
    { code: 'LV', dialCode: '+371', flag: '🇱🇻', name: 'Latvia' },
    { code: 'LB', dialCode: '+961', flag: '🇱🇧', name: 'Lebanon' },
    { code: 'LS', dialCode: '+266', flag: '🇱🇸', name: 'Lesotho' },
    { code: 'LR', dialCode: '+231', flag: '🇱🇷', name: 'Liberia' },
    { code: 'LY', dialCode: '+218', flag: '🇱🇾', name: 'Libya' },
    { code: 'LI', dialCode: '+423', flag: '🇱🇮', name: 'Liechtenstein' },
    { code: 'LT', dialCode: '+370', flag: '🇱🇹', name: 'Lithuania' },
    { code: 'LU', dialCode: '+352', flag: '🇱🇺', name: 'Luxembourg' },
    { code: 'MO', dialCode: '+853', flag: '🇲🇴', name: 'Macau' },
    { code: 'MK', dialCode: '+389', flag: '🇲🇰', name: 'Macedonia' },
    { code: 'MG', dialCode: '+261', flag: '🇲🇬', name: 'Madagascar' },
    { code: 'MW', dialCode: '+265', flag: '🇲🇼', name: 'Malawi' },
    { code: 'MY', dialCode: '+60', flag: '🇲🇾', name: 'Malaysia' },
    { code: 'MV', dialCode: '+960', flag: '🇲🇻', name: 'Maldives' },
    { code: 'ML', dialCode: '+223', flag: '🇲🇱', name: 'Mali' },
    { code: 'MT', dialCode: '+356', flag: '🇲🇹', name: 'Malta' },
    { code: 'MH', dialCode: '+692', flag: '🇲🇭', name: 'Marshall Islands' },
    { code: 'MR', dialCode: '+222', flag: '🇲🇷', name: 'Mauritania' },
    { code: 'MU', dialCode: '+230', flag: '🇲🇺', name: 'Mauritius' },
    { code: 'YT', dialCode: '+262', flag: '🇾🇹', name: 'Mayotte' },
    { code: 'MX', dialCode: '+52', flag: '🇲🇽', name: 'Mexico' },
    { code: 'FM', dialCode: '+691', flag: '🇫🇲', name: 'Micronesia' },
    { code: 'MD', dialCode: '+373', flag: '🇲🇩', name: 'Moldova' },
    { code: 'MC', dialCode: '+377', flag: '🇲🇨', name: 'Monaco' },
    { code: 'MN', dialCode: '+976', flag: '🇲🇳', name: 'Mongolia' },
    { code: 'ME', dialCode: '+382', flag: '🇲🇪', name: 'Montenegro' },
    { code: 'MS', dialCode: '+1664', flag: '🇲🇸', name: 'Montserrat' },
    { code: 'MA', dialCode: '+212', flag: '🇲🇦', name: 'Morocco' },
    { code: 'MZ', dialCode: '+258', flag: '🇲🇿', name: 'Mozambique' },
    { code: 'MM', dialCode: '+95', flag: '🇲🇲', name: 'Myanmar' },
    { code: 'NA', dialCode: '+264', flag: '🇳🇦', name: 'Namibia' },
    { code: 'NR', dialCode: '+674', flag: '🇳🇷', name: 'Nauru' },
    { code: 'NP', dialCode: '+977', flag: '🇳🇵', name: 'Nepal' },
    { code: 'NL', dialCode: '+31', flag: '🇳🇱', name: 'Netherlands' },
    { code: 'NC', dialCode: '+687', flag: '🇳🇨', name: 'New Caledonia' },
    { code: 'NZ', dialCode: '+64', flag: '🇳🇿', name: 'New Zealand' },
    { code: 'NI', dialCode: '+505', flag: '🇳🇮', name: 'Nicaragua' },
    { code: 'NE', dialCode: '+227', flag: '🇳🇪', name: 'Niger' },
    { code: 'NG', dialCode: '+234', flag: '🇳🇬', name: 'Nigeria' },
    { code: 'NU', dialCode: '+683', flag: '🇳🇺', name: 'Niue' },
    { code: 'NF', dialCode: '+672', flag: '🇳🇫', name: 'Norfolk Island' },
    { code: 'KP', dialCode: '+850', flag: '🇰🇵', name: 'North Korea' },
    { code: 'MP', dialCode: '+1670', flag: '🇲🇵', name: 'Northern Mariana Islands' },
    { code: 'NO', dialCode: '+47', flag: '🇳🇴', name: 'Norway' },
    { code: 'OM', dialCode: '+968', flag: '🇴🇲', name: 'Oman' },
    { code: 'PK', dialCode: '+92', flag: '🇵🇰', name: 'Pakistan' },
    { code: 'PW', dialCode: '+680', flag: '🇵🇼', name: 'Palau' },
    { code: 'PS', dialCode: '+970', flag: '🇵🇸', name: 'Palestine' },
    { code: 'PA', dialCode: '+507', flag: '🇵🇦', name: 'Panama' },
    { code: 'PG', dialCode: '+675', flag: '🇵🇬', name: 'Papua New Guinea' },
    { code: 'PY', dialCode: '+595', flag: '🇵🇾', name: 'Paraguay' },
    { code: 'PE', dialCode: '+51', flag: '🇵🇪', name: 'Peru' },
    { code: 'PH', dialCode: '+63', flag: '🇵🇭', name: 'Philippines' },
    { code: 'PN', dialCode: '+64', flag: '🇵🇳', name: 'Pitcairn' },
    { code: 'PL', dialCode: '+48', flag: '🇵🇱', name: 'Poland' },
    { code: 'PT', dialCode: '+351', flag: '🇵🇹', name: 'Portugal' },
    { code: 'PR', dialCode: '+1787', flag: '🇵🇷', name: 'Puerto Rico' },
    { code: 'QA', dialCode: '+974', flag: '🇶🇦', name: 'Qatar' },
    { code: 'CG', dialCode: '+242', flag: '🇨🇬', name: 'Republic of the Congo' },
    { code: 'RO', dialCode: '+40', flag: '🇷🇴', name: 'Romania' },
    { code: 'RU', dialCode: '+7', flag: '🇷🇺', name: 'Russia' },
    { code: 'RW', dialCode: '+250', flag: '🇷🇼', name: 'Rwanda' },
    { code: 'RE', dialCode: '+262', flag: '🇷🇪', name: 'Réunion' },
    { code: 'BL', dialCode: '+590', flag: '🇧🇱', name: 'Saint Barthélemy' },
    { code: 'SH', dialCode: '+290', flag: '🇸🇭', name: 'Saint Helena' },
    { code: 'KN', dialCode: '+1869', flag: '🇰🇳', name: 'Saint Kitts and Nevis' },
    { code: 'LC', dialCode: '+1758', flag: '🇱🇨', name: 'Saint Lucia' },
    { code: 'MF', dialCode: '+590', flag: '🇲🇫', name: 'Saint Martin' },
    { code: 'PM', dialCode: '+508', flag: '🇵🇲', name: 'Saint Pierre and Miquelon' },
    { code: 'VC', dialCode: '+1784', flag: '🇻🇨', name: 'Saint Vincent and the Grenadines' },
    { code: 'WS', dialCode: '+685', flag: '🇼🇸', name: 'Samoa' },
    { code: 'SM', dialCode: '+378', flag: '🇸🇲', name: 'San Marino' },
    { code: 'ST', dialCode: '+239', flag: '🇸🇹', name: 'Sao Tome and Principe' },
    { code: 'SA', dialCode: '+966', flag: '🇸🇦', name: 'Saudi Arabia' },
    { code: 'SN', dialCode: '+221', flag: '🇸🇳', name: 'Senegal' },
    { code: 'RS', dialCode: '+381', flag: '🇷🇸', name: 'Serbia' },
    { code: 'SC', dialCode: '+248', flag: '🇸🇨', name: 'Seychelles' },
    { code: 'SL', dialCode: '+232', flag: '🇸🇱', name: 'Sierra Leone' },
    { code: 'SG', dialCode: '+65', flag: '🇸🇬', name: 'Singapore' },
    { code: 'SX', dialCode: '+1721', flag: '🇸🇽', name: 'Sint Maarten' },
    { code: 'SK', dialCode: '+421', flag: '🇸🇰', name: 'Slovakia' },
    { code: 'SI', dialCode: '+386', flag: '🇸🇮', name: 'Slovenia' },
    { code: 'SB', dialCode: '+677', flag: '🇸🇧', name: 'Solomon Islands' },
    { code: 'SO', dialCode: '+252', flag: '🇸🇴', name: 'Somalia' },
    { code: 'ZA', dialCode: '+27', flag: '🇿🇦', name: 'South Africa' },
    { code: 'KR', dialCode: '+82', flag: '🇰🇷', name: 'South Korea' },
    { code: 'SS', dialCode: '+211', flag: '🇸🇸', name: 'South Sudan' },
    { code: 'ES', dialCode: '+34', flag: '🇪🇸', name: 'Spain' },
    { code: 'LK', dialCode: '+94', flag: '🇱🇰', name: 'Sri Lanka' },
    { code: 'SD', dialCode: '+249', flag: '🇸🇩', name: 'Sudan' },
    { code: 'SR', dialCode: '+597', flag: '🇸🇷', name: 'Suriname' },
    { code: 'SJ', dialCode: '+47', flag: '🇸🇯', name: 'Svalbard and Jan Mayen' },
    { code: 'SZ', dialCode: '+268', flag: '🇸🇿', name: 'Swaziland' },
    { code: 'SE', dialCode: '+46', flag: '🇸🇪', name: 'Sweden' },
    { code: 'CH', dialCode: '+41', flag: '🇨🇭', name: 'Switzerland' },
    { code: 'SY', dialCode: '+963', flag: '🇸🇾', name: 'Syria' },
    { code: 'TW', dialCode: '+886', flag: '🇹🇼', name: 'Taiwan' },
    { code: 'TJ', dialCode: '+992', flag: '🇹🇯', name: 'Tajikistan' },
    { code: 'TZ', dialCode: '+255', flag: '🇹🇿', name: 'Tanzania' },
    { code: 'TH', dialCode: '+66', flag: '🇹🇭', name: 'Thailand' },
    { code: 'TG', dialCode: '+228', flag: '🇹🇬', name: 'Togo' },
    { code: 'TK', dialCode: '+690', flag: '🇹🇰', name: 'Tokelau' },
    { code: 'TO', dialCode: '+676', flag: '🇹🇴', name: 'Tonga' },
    { code: 'TT', dialCode: '+1868', flag: '🇹🇹', name: 'Trinidad and Tobago' },
    { code: 'TN', dialCode: '+216', flag: '🇹🇳', name: 'Tunisia' },
    { code: 'TR', dialCode: '+90', flag: '🇹🇷', name: 'Turkey' },
    { code: 'TM', dialCode: '+993', flag: '🇹🇲', name: 'Turkmenistan' },
    { code: 'TC', dialCode: '+1649', flag: '🇹🇨', name: 'Turks and Caicos Islands' },
    { code: 'TV', dialCode: '+688', flag: '🇹🇻', name: 'Tuvalu' },
    { code: 'VI', dialCode: '+1340', flag: '🇻🇮', name: 'U.S. Virgin Islands' },
    { code: 'UG', dialCode: '+256', flag: '🇺🇬', name: 'Uganda' },
    { code: 'UA', dialCode: '+380', flag: '🇺🇦', name: 'Ukraine' },
    { code: 'AE', dialCode: '+971', flag: '🇦🇪', name: 'United Arab Emirates' },
    { code: 'GB', dialCode: '+44', flag: '🇬🇧', name: 'United Kingdom' },
    { code: 'US', dialCode: '+1', flag: '🇺🇸', name: 'United States' },
    { code: 'UY', dialCode: '+598', flag: '🇺🇾', name: 'Uruguay' },
    { code: 'UZ', dialCode: '+998', flag: '🇺🇿', name: 'Uzbekistan' },
    { code: 'VU', dialCode: '+678', flag: '🇻🇺', name: 'Vanuatu' },
    { code: 'VA', dialCode: '+39', flag: '🇻🇦', name: 'Vatican City' },
    { code: 'VE', dialCode: '+58', flag: '🇻🇪', name: 'Venezuela' },
    { code: 'VN', dialCode: '+84', flag: '🇻🇳', name: 'Vietnam' },
    { code: 'WF', dialCode: '+681', flag: '🇼🇫', name: 'Wallis and Futuna' },
    { code: 'EH', dialCode: '+212', flag: '🇪🇭', name: 'Western Sahara' },
    { code: 'YE', dialCode: '+967', flag: '🇾🇪', name: 'Yemen' },
    { code: 'ZM', dialCode: '+260', flag: '🇿🇲', name: 'Zambia' },
    { code: 'ZW', dialCode: '+263', flag: '🇿🇼', name: 'Zimbabwe' },
];
