export interface Vaccine {
  id: string;
  brandName: string;
  type: string;
  protectsAgainst: string;
  genericName: string;
  petType: 'Dog' | 'Cat' | 'Rabbit' | 'Ferret' | 'Pigeon' | 'Parrot' | 'Both';
  duration: string;
  description: string;
  category: string;
  route: string;
  core: 'Core' | 'Non-Core';
}

export const VACCINES: Vaccine[] = [
  {
    id: 'nobivac-rabies-dog-1',
    brandName: 'Nobivac Rabies',
    type: 'Vaccine',
    protectsAgainst: 'Rabies',
    genericName: 'Rabies Vaccine',
    petType: 'Dog',
    duration: '1 year',
    description: 'Core vaccine for rabies protection; requires annual booster after initial series and 1-year booster',
    category: 'Core',
    route: 'Subcutaneous Injection',
    core: 'Core'
  },
  {
    id: 'nobivac-rabies-dog-3',
    brandName: 'Nobivac Rabies',
    type: 'Vaccine',
    protectsAgainst: 'Rabies',
    genericName: 'Rabies Vaccine',
    petType: 'Dog',
    duration: '3 years',
    description: 'Core vaccine for rabies protection; provides 3-year immunity after initial 1-year booster',
    category: 'Core',
    route: 'Subcutaneous Injection',
    core: 'Core'
  },
  {
    id: 'nobivac-rabies-cat-1',
    brandName: 'Nobivac Rabies',
    type: 'Vaccine',
    protectsAgainst: 'Rabies',
    genericName: 'Rabies Vaccine',
    petType: 'Cat',
    duration: '1 year',
    description: 'Core vaccine for rabies protection in cats; annual booster required',
    category: 'Core',
    route: 'Subcutaneous Injection',
    core: 'Core'
  },
  {
    id: 'nobivac-rabies-cat-3',
    brandName: 'Nobivac Rabies',
    type: 'Vaccine',
    protectsAgainst: 'Rabies',
    genericName: 'Rabies Vaccine',
    petType: 'Cat',
    duration: '3 years',
    description: 'Core vaccine for rabies protection in cats; 3-year immunity after initial booster',
    category: 'Core',
    route: 'Subcutaneous Injection',
    core: 'Core'
  },
  {
    id: 'imrab-1-dog',
    brandName: 'IMRAB 1 TF',
    type: 'Vaccine',
    protectsAgainst: 'Rabies',
    genericName: 'Rabies Vaccine',
    petType: 'Dog',
    duration: '1 year',
    description: 'Rabies vaccine with 1-year duration; required annual revaccination',
    category: 'Core',
    route: 'Subcutaneous Injection',
    core: 'Core'
  },
  {
    id: 'imrab-1-cat',
    brandName: 'IMRAB 1 TF',
    type: 'Vaccine',
    protectsAgainst: 'Rabies',
    genericName: 'Rabies Vaccine',
    petType: 'Cat',
    duration: '1 year',
    description: 'Rabies vaccine for cats with 1-year duration; annual booster needed',
    category: 'Core',
    route: 'Subcutaneous Injection',
    core: 'Core'
  },
  {
    id: 'imrab-3-dog',
    brandName: 'IMRAB 3 TF',
    type: 'Vaccine',
    protectsAgainst: 'Rabies',
    genericName: 'Rabies Vaccine',
    petType: 'Dog',
    duration: '3 years',
    description: 'Rabies vaccine providing 3-year immunity after 1-year booster',
    category: 'Core',
    route: 'Subcutaneous Injection',
    core: 'Core'
  },
  {
    id: 'imrab-3-cat',
    brandName: 'IMRAB 3 TF',
    type: 'Vaccine',
    protectsAgainst: 'Rabies',
    genericName: 'Rabies Vaccine',
    petType: 'Cat',
    duration: '3 years',
    description: 'Rabies vaccine for cats with 3-year duration option',
    category: 'Core',
    route: 'Subcutaneous Injection',
    core: 'Core'
  },
  {
    id: 'defensor-1',
    brandName: 'Defensor',
    type: 'Vaccine',
    protectsAgainst: 'Rabies',
    genericName: 'Rabies Vaccine',
    petType: 'Dog',
    duration: '1 year',
    description: 'Annual rabies vaccine for dogs; legal requirement in many jurisdictions',
    category: 'Core',
    route: 'Subcutaneous Injection',
    core: 'Core'
  },
  {
    id: 'defensor-3',
    brandName: 'Defensor',
    type: 'Vaccine',
    protectsAgainst: 'Rabies',
    genericName: 'Rabies Vaccine',
    petType: 'Dog',
    duration: '3 years',
    description: 'Rabies vaccine providing 3-year protection after initial series',
    category: 'Core',
    route: 'Subcutaneous Injection',
    core: 'Core'
  },
  {
    id: 'purevax-rabies-1',
    brandName: 'PureVax Rabies',
    type: 'Vaccine',
    protectsAgainst: 'Rabies',
    genericName: 'Rabies Vaccine',
    petType: 'Cat',
    duration: '1 year',
    description: 'Non-adjuvanted rabies vaccine; reduces injection site sarcoma risk in cats; annual booster',
    category: 'Core',
    route: 'Subcutaneous Injection',
    core: 'Core'
  },
  {
    id: 'purevax-rabies-3',
    brandName: 'PureVax Rabies',
    type: 'Vaccine',
    protectsAgainst: 'Rabies',
    genericName: 'Rabies Vaccine',
    petType: 'Cat',
    duration: '3 years',
    description: 'Non-adjuvanted rabies vaccine with 3-year duration for cats',
    category: 'Core',
    route: 'Subcutaneous Injection',
    core: 'Core'
  },
  {
    id: 'nobivac-dappv-1',
    brandName: 'Nobivac Canine 1-DAPPv',
    type: 'Vaccine',
    protectsAgainst: 'Distemper/Parvovirus/Adenovirus/Parainfluenza',
    genericName: 'DHPP Vaccine',
    petType: 'Dog',
    duration: '1 year',
    description: 'Core vaccine protecting against canine distemper; annual revaccination protocol recommended',
    category: 'Core',
    route: 'Subcutaneous Injection',
    core: 'Core'
  },
  {
    id: 'nobivac-dappv-3',
    brandName: 'Nobivac Canine 1-DAPPv',
    type: 'Vaccine',
    protectsAgainst: 'Distemper/Parvovirus/Adenovirus/Parainfluenza',
    genericName: 'DHPP Vaccine',
    petType: 'Dog',
    duration: '3 years',
    description: 'Core vaccine with extended 3-year duration after initial booster',
    category: 'Core',
    route: 'Subcutaneous Injection',
    core: 'Core'
  },
  {
    id: 'vanguard-plus-5',
    brandName: 'Vanguard Plus 5',
    type: 'Vaccine',
    protectsAgainst: 'Distemper/Parvovirus/Adenovirus/Parainfluenza/Coronavirus',
    genericName: 'DA2PPv+CV Vaccine',
    petType: 'Dog',
    duration: '3 years',
    description: 'Core vaccine with coronavirus protection; 3-year immunity protocol',
    category: 'Core',
    route: 'Subcutaneous Injection',
    core: 'Core'
  },
  {
    id: 'vanguard-plus-l4r',
    brandName: 'Vanguard Plus DHPPi/L4R',
    type: 'Vaccine',
    protectsAgainst: 'Distemper/Adenovirus/Parainfluenza/Parvovirus/Leptospirosis/Rabies',
    genericName: 'DHPPi/L4R+Rabies Vaccine',
    petType: 'Dog',
    duration: '3 years',
    description: 'Combination vaccine protecting against core vaccines plus leptospirosis and rabies; 3-year duration',
    category: 'Core',
    route: 'Subcutaneous Injection',
    core: 'Core'
  },
  {
    id: 'duramune-max',
    brandName: 'Duramune Max 5-CvK/4L',
    type: 'Vaccine',
    protectsAgainst: 'Distemper/Adenovirus/Parainfluenza/Parvovirus/Coronavirus/Leptospirosis',
    genericName: 'DA2PPv+CV+L Vaccine',
    petType: 'Dog',
    duration: '1 year',
    description: 'Annual canine vaccine with coronavirus and leptospirosis protection; requires annual revaccination',
    category: 'Core',
    route: 'Subcutaneous Injection',
    core: 'Core'
  },
  {
    id: 'nobivac-feline-1',
    brandName: 'Nobivac Feline',
    type: 'Vaccine',
    protectsAgainst: 'Feline Viral Rhinotracheitis/Calicivirus/Panleukopenia',
    genericName: 'FVRCP Vaccine',
    petType: 'Cat',
    duration: '1 year',
    description: 'Core vaccine protecting against FHV-1; calicivirus and panleukopenia; annual protocol',
    category: 'Core',
    route: 'Subcutaneous Injection',
    core: 'Core'
  },
  {
    id: 'nobivac-feline-3',
    brandName: 'Nobivac Feline',
    type: 'Vaccine',
    protectsAgainst: 'Feline Viral Rhinotracheitis/Calicivirus/Panleukopenia',
    genericName: 'FVRCP Vaccine',
    petType: 'Cat',
    duration: '3 years',
    description: 'Core vaccine with 3-year immunity after initial booster series',
    category: 'Core',
    route: 'Subcutaneous Injection',
    core: 'Core'
  },
  {
    id: 'felocell-3',
    brandName: 'Felocell 3',
    type: 'Vaccine',
    protectsAgainst: 'Feline Viral Rhinotracheitis/Calicivirus/Panleukopenia',
    genericName: 'FVRCP Vaccine',
    petType: 'Cat',
    duration: '3 years',
    description: 'Core feline vaccine; 3-year protection after initial series; may cause mild fever',
    category: 'Core',
    route: 'Subcutaneous Injection',
    core: 'Core'
  },
  {
    id: 'felocell-4',
    brandName: 'Felocell 4',
    type: 'Vaccine',
    protectsAgainst: 'Feline Viral Rhinotracheitis/Calicivirus/Panleukopenia/Chlamydia',
    genericName: 'FVRCP-C Vaccine',
    petType: 'Cat',
    duration: '3 years',
    description: 'Core vaccine plus chlamydia protection for cats with respiratory risk; 3-year duration',
    category: 'Core',
    route: 'Subcutaneous Injection',
    core: 'Core'
  },
  {
    id: 'purevax-feline-3-1',
    brandName: 'PureVax Feline 3',
    type: 'Vaccine',
    protectsAgainst: 'Feline Viral Rhinotracheitis/Calicivirus/Panleukopenia',
    genericName: 'FVRCP Vaccine',
    petType: 'Cat',
    duration: '1 year',
    description: 'Non-adjuvanted vaccine; reduces injection site reactions; annual protocol then 3-year boosters',
    category: 'Core',
    route: 'Subcutaneous Injection',
    core: 'Core'
  },
  {
    id: 'purevax-feline-3-3',
    brandName: 'PureVax Feline 3',
    type: 'Vaccine',
    protectsAgainst: 'Feline Viral Rhinotracheitis/Calicivirus/Panleukopenia',
    genericName: 'FVRCP Vaccine',
    petType: 'Cat',
    duration: '3 years',
    description: 'Non-adjuvanted vaccine with 3-year duration after initial booster',
    category: 'Core',
    route: 'Subcutaneous Injection',
    core: 'Core'
  },
  {
    id: 'nobivac-lepto',
    brandName: 'Nobivac Lepto 4',
    type: 'Vaccine',
    protectsAgainst: 'Leptospirosis',
    genericName: 'Leptospira Vaccine',
    petType: 'Dog',
    duration: '1 year',
    description: 'Non-core vaccine protecting against 4 leptospirosis serovars; annual revaccination in endemic areas',
    category: 'Non-Core',
    route: 'Subcutaneous Injection',
    core: 'Non-Core'
  },
  {
    id: 'nobivac-kc',
    brandName: 'Nobivac KC',
    type: 'Vaccine',
    protectsAgainst: 'Kennel Cough',
    genericName: 'Bordetella Vaccine',
    petType: 'Dog',
    duration: '1 year',
    description: 'Non-core vaccine recommended for boarding/daycare dogs; protects against infectious tracheobronchitis',
    category: 'Non-Core',
    route: 'Intranasal',
    core: 'Non-Core'
  },
  {
    id: 'nobivac-lyme',
    brandName: 'Nobivac Lyme',
    type: 'Vaccine',
    protectsAgainst: 'Lyme Disease',
    genericName: 'Borrelia Vaccine',
    petType: 'Dog',
    duration: '1 year',
    description: 'Non-core vaccine for Lyme disease; recommended in tick-endemic regions; annual booster',
    category: 'Non-Core',
    route: 'Subcutaneous Injection',
    core: 'Non-Core'
  },
  {
    id: 'nobivac-felv',
    brandName: 'Nobivac FeLV',
    type: 'Vaccine',
    protectsAgainst: 'Feline Leukemia Virus',
    genericName: 'FeLV Vaccine',
    petType: 'Cat',
    duration: '1 year',
    description: 'Non-core vaccine for outdoor and at-risk cats; annual booster in first year',
    category: 'Non-Core',
    route: 'Subcutaneous Injection',
    core: 'Non-Core'
  },
  {
    id: 'purevax-felv',
    brandName: 'PureVax FeLV',
    type: 'Vaccine',
    protectsAgainst: 'Feline Leukemia Virus',
    genericName: 'FeLV Vaccine',
    petType: 'Cat',
    duration: '1 year',
    description: 'Non-adjuvanted FeLV vaccine; reduces injection site reactions; annual protocol',
    category: 'Non-Core',
    route: 'Subcutaneous Injection',
    core: 'Non-Core'
  }
];
