-- Create breeds table
create table if not exists public.breeds (
  id uuid primary key default gen_random_uuid(),
  species text not null check (species in ('dog','cat')),
  name text not null
);

-- Indexes for performance
create index if not exists breeds_species_idx on public.breeds (species);
drop index if exists public.breeds_species_name_idx;
create unique index if not exists breeds_species_name_unique_idx on public.breeds (species, name);

-- Seed dog breeds (subset; extend as needed)
insert into public.breeds (species, name) values
('dog','Mixed Breed'),
('dog','Labrador Retriever'),
('dog','German Shepherd'),
('dog','Golden Retriever'),
('dog','French Bulldog'),
('dog','Bulldog'),
('dog','Poodle'),
('dog','Beagle'),
('dog','Rottweiler'),
('dog','Yorkshire Terrier'),
('dog','Chihuahua'),
('dog','Dachshund'),
('dog','Boxer'),
('dog','Siberian Husky'),
('dog','Great Dane'),
('dog','Doberman Pinscher'),
('dog','Shih Tzu'),
('dog','Miniature Schnauzer'),
('dog','Cocker Spaniel'),
('dog','Border Collie'),
('dog','Australian Shepherd'),
('dog','Cavalier King Charles Spaniel'),
('dog','Pembroke Welsh Corgi'),
('dog','Pug'),
('dog','Mastiff'),
('dog','Bernese Mountain Dog'),
('dog','Bichon Frise'),
('dog','Akita'),
('dog','Dalmatian'),
('dog','Samoyed'),
('dog','Afghan Hound'),
('dog','Whippet'),
('dog','Weimaraner'),
('dog','Boston Terrier'),
('dog','Havanese'),
('dog','Maltese'),
('dog','English Springer Spaniel'),
('dog','Vizsla'),
('dog','Newfoundland'),
('dog','Greyhound'),
('dog','Shar-Pei'),
('dog','Scottish Terrier'),
('dog','Irish Setter'),
('dog','Bull Terrier'),
('dog','Bloodhound'),
('dog','Alaskan Malamute'),
('dog','Airedale Terrier'),
('dog','Basenji'),
('dog','Papillon'),
('dog','Lhasa Apso'),
('dog','Affenpinscher'),
('dog','Airedale Terrier'),
('dog','American Bulldog'),
('dog','American English Coonhound'),
('dog','American Eskimo Dog'),
('dog','American Foxhound'),
('dog','American Hairless Terrier'),
('dog','American Staffordshire Terrier'),
('dog','American Water Spaniel'),
('dog','Anatolian Shepherd Dog'),
('dog','Australian Cattle Dog'),
('dog','Australian Terrier'),
('dog','Azawakh'),
('dog','Basset Hound'),
('dog','Bearded Collie'),
('dog','Beauceron'),
('dog','Bedlington Terrier'),
('dog','Belgian Malinois'),
('dog','Belgian Sheepdog'),
('dog','Belgian Tervuren'),
('dog','Belgian Laekenois'),
('dog','Bergamasco'),
('dog','Berger Picard'),
('dog','Black and Tan Coonhound'),
('dog','Black Russian Terrier'),
('dog','Bluetick Coonhound'),
('dog','Boerboel'),
('dog','Border Terrier'),
('dog','Borzoi'),
('dog','Bouvier des Flandres'),
('dog','Boykin Spaniel'),
('dog','Briard'),
('dog','Brittany'),
('dog','Brussels Griffon'),
('dog','Bullmastiff'),
('dog','Cairn Terrier'),
('dog','Canaan Dog'),
('dog','Cane Corso'),
('dog','Cardigan Welsh Corgi'),
('dog','Cesky Terrier'),
('dog','Chesapeake Bay Retriever'),
('dog','Chinese Crested'),
('dog','Chinese Shar-Pei'),
('dog','Chinook'),
('dog','Cirneco dell\'Etna'),
('dog','Clumber Spaniel'),
('dog','Collie'),
('dog','Coton de Tulear'),
('dog','Curly-Coated Retriever'),
('dog','Dandie Dinmont Terrier'),
('dog','Doberman Pinscher'),
('dog','Dogo Argentino'),
('dog','Dogue de Bordeaux'),
('dog','English Cocker Spaniel'),
('dog','English Foxhound'),
('dog','English Setter'),
('dog','English Springer Spaniel'),
('dog','English Toy Spaniel'),
('dog','Entlebucher Mountain Dog'),
('dog','Field Spaniel'),
('dog','Finnish Lapphund'),
('dog','Finnish Spitz'),
('dog','Flat-Coated Retriever'),
('dog','French Bulldog'),
('dog','German Pinscher'),
('dog','German Shorthaired Pointer'),
('dog','German Wirehaired Pointer'),
('dog','Giant Schnauzer'),
('dog','Glen of Imaal Terrier'),
('dog','Gordon Setter'),
('dog','Great Pyrenees'),
('dog','Greater Swiss Mountain Dog'),
('dog','Harrier'),
('dog','Ibizan Hound'),
('dog','Icelandic Sheepdog'),
('dog','Irish Terrier'),
('dog','Irish Water Spaniel'),
('dog','Irish Wolfhound'),
('dog','Italian Greyhound'),
('dog','Japanese Chin'),
('dog','Keeshond'),
('dog','Kerry Blue Terrier'),
('dog','Komondor'),
('dog','Kuvasz'),
('dog','Lagotto Romagnolo'),
('dog','Lakeland Terrier'),
('dog','Leonberger'),
('dog','Lhasa Apso'),
('dog','Lowchen'),
('dog','Maltese'),
('dog','Manchester Terrier'),
('dog','Miniature American Shepherd'),
('dog','Miniature Bull Terrier'),
('dog','Miniature Pinscher'),
('dog','Miniature Schnauzer'),
('dog','Neapolitan Mastiff'),
('dog','Newfoundland'),
('dog','Norfolk Terrier'),
('dog','Norwegian Buhund'),
('dog','Norwegian Elkhound'),
('dog','Norwegian Lundehund'),
('dog','Norwich Terrier'),
('dog','Nova Scotia Duck Tolling Retriever'),
('dog','Old English Sheepdog'),
('dog','Otterhound'),
('dog','Papillon'),
('dog','Parson Russell Terrier'),
('dog','Pekingese'),
('dog','Pembroke Welsh Corgi'),
('dog','Peruvian Inca Orchid'),
('dog','Petit Basset Griffon Vendeen'),
('dog','Pharaoh Hound'),
('dog','Plott Hound'),
('dog','Pointer'),
('dog','Polish Lowland Sheepdog'),
('dog','Pomeranian'),
('dog','Portuguese Podengo'),
('dog','Portuguese Podengo Pequeno'),
('dog','Portuguese Water Dog'),
('dog','Puli'),
('dog','Pumi'),
('dog','Rat Terrier'),
('dog','Redbone Coonhound'),
('dog','Rhodesian Ridgeback'),
('dog','Russell Terrier'),
('dog','Saint Bernard'),
('dog','Saluki'),
('dog','Schipperke'),
('dog','Scottish Deerhound'),
('dog','Scottish Terrier'),
('dog','Sealyham Terrier'),
('dog','Shetland Sheepdog'),
('dog','Shiba Inu'),
('dog','Shih Tzu'),
('dog','Siberian Husky'),
('dog','Silky Terrier'),
('dog','Skye Terrier'),
('dog','Soft Coated Wheaten Terrier'),
('dog','Spanish Water Dog'),
('dog','Spinone Italiano'),
('dog','Staffordshire Bull Terrier'),
('dog','Standard Schnauzer'),
('dog','Sussex Spaniel'),
('dog','Tibetan Mastiff'),
('dog','Tibetan Spaniel'),
('dog','Tibetan Terrier'),
('dog','Toy Fox Terrier'),
('dog','Treeing Walker Coonhound'),
('dog','Vizsla'),
('dog','Weimaraner'),
('dog','Welsh Springer Spaniel'),
('dog','Welsh Terrier'),
('dog','West Highland White Terrier'),
('dog','Whippet'),
('dog','Wirehaired Pointing Griffon'),
('dog','Wirehaired Vizsla'),
('dog','Xoloitzcuintli'),
('dog','Yorkshire Terrier'),
('dog','Alaskan Klee Kai'),
('dog','Lancashire Heeler'),
('dog','Mudi')
on conflict do nothing;

-- Seed cat breeds (subset; extend as needed)
insert into public.breeds (species, name) values
('cat','Mixed'),
('cat','Domestic Short Hair'),
('cat','Domestic Long Hair'),
('cat','Siamese'),
('cat','Persian'),
('cat','Maine Coon'),
('cat','British Shorthair'),
('cat','Bengal'),
('cat','Sphynx'),
('cat','Ragdoll'),
('cat','Scottish Fold'),
('cat','Russian Blue'),
('cat','American Shorthair'),
('cat','Norwegian Forest Cat'),
('cat','Abyssinian'),
('cat','Birman'),
('cat','Savannah'),
('cat','Oriental'),
('cat','Tonkinese'),
('cat','Selkirk Rex'),
('cat','Cornish Rex'),
('cat','Devon Rex'),
('cat','Turkish Van'),
('cat','Himalayan'),
('cat','Egyptian Mau'),
('cat','Chartreux'),
('cat','Manx'),
('cat','Somali'),
('cat','Nebelung'),
('cat','Balinese'),
('cat','American Bobtail'),
('cat','American Curl'),
('cat','American Wirehair'),
('cat','Burmese'),
('cat','Burmilla'),
('cat','Colorpoint Shorthair'),
('cat','European Burmese'),
('cat','Exotic'),
('cat','Havana Brown'),
('cat','Japanese Bobtail'),
('cat','Korat'),
('cat','LaPerm'),
('cat','Ocicat'),
('cat','Oriental Shorthair'),
('cat','Oriental Longhair'),
('cat','Ragamuffin'),
('cat','Selkirk Rex'),
('cat','Siberian'),
('cat','Singapura'),
('cat','Turkish Angora')
on conflict do nothing;
