-- Create reference_breeds table
CREATE TABLE IF NOT EXISTS public.reference_breeds (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    species TEXT NOT NULL CHECK (species IN ('dog', 'cat')),
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.reference_breeds ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Public read access for reference_breeds"
    ON public.reference_breeds
    FOR SELECT
    USING (true);

-- Insert Dog Breeds
INSERT INTO public.reference_breeds (species, name) VALUES
('dog', 'Affenpinscher'),
('dog', 'Afghan Hound'),
('dog', 'Airedale Terrier'),
('dog', 'Akita'),
('dog', 'Alaskan Klee Kai'),
('dog', 'Alaskan Malamute'),
('dog', 'American Bulldog'),
('dog', 'American English Coonhound'),
('dog', 'American Eskimo Dog'),
('dog', 'American Foxhound'),
('dog', 'American Hairless Terrier'),
('dog', 'American Leopard Hound'),
('dog', 'American Staffordshire Terrier'),
('dog', 'American Water Spaniel'),
('dog', 'Anatolian Shepherd Dog'),
('dog', 'Appenzeller Sennenhund'),
('dog', 'Australian Cattle Dog'),
('dog', 'Australian Kelpie'),
('dog', 'Australian Shepherd'),
('dog', 'Australian Stumpy Tail Cattle Dog'),
('dog', 'Australian Terrier'),
('dog', 'Azawakh'),
('dog', 'Barbet'),
('dog', 'Basenji'),
('dog', 'Basset Fauve de Bretagne'),
('dog', 'Basset Hound'),
('dog', 'Bavarian Mountain Scent Hound'),
('dog', 'Beagle'),
('dog', 'Bearded Collie'),
('dog', 'Beauceron'),
('dog', 'Bedlington Terrier'),
('dog', 'Belgian Laekenois'),
('dog', 'Belgian Malinois'),
('dog', 'Belgian Sheepdog'),
('dog', 'Belgian Tervuren'),
('dog', 'Bergamasco Sheepdog'),
('dog', 'Berger Picard'),
('dog', 'Bernese Mountain Dog'),
('dog', 'Bichon Frise'),
('dog', 'Biewer Terrier'),
('dog', 'Black and Tan Coonhound'),
('dog', 'Black Russian Terrier'),
('dog', 'Bloodhound'),
('dog', 'Bluetick Coonhound'),
('dog', 'Boerboel'),
('dog', 'Bohemian Shepherd'),
('dog', 'Bolognese'),
('dog', 'Border Collie'),
('dog', 'Border Terrier'),
('dog', 'Borzoi'),
('dog', 'Boston Terrier'),
('dog', 'Bouvier des Flandres'),
('dog', 'Boxer'),
('dog', 'Boykin Spaniel'),
('dog', 'Bracco Italiano'),
('dog', 'Braque du Bourbonnais'),
('dog', 'Braque Francais Pyrenean'),
('dog', 'Briard'),
('dog', 'Brittany'),
('dog', 'Broholmer'),
('dog', 'Brussels Griffon'),
('dog', 'Bull Terrier'),
('dog', 'Bulldog'),
('dog', 'Bullmastiff'),
('dog', 'Cairn Terrier'),
('dog', 'Canaan Dog'),
('dog', 'Cane Corso'),
('dog', 'Cardigan Welsh Corgi'),
('dog', 'Catahoula Leopard Dog'),
('dog', 'Caucasian Shepherd Dog'),
('dog', 'Cavalier King Charles Spaniel'),
('dog', 'Central Asian Shepherd Dog'),
('dog', 'Cesky Terrier'),
('dog', 'Chesapeake Bay Retriever'),
('dog', 'Chihuahua'),
('dog', 'Chinese Crested'),
('dog', 'Chinese Shar-Pei'),
('dog', 'Chinook'),
('dog', 'Chow Chow'),
('dog', 'Cirneco dell’Etna'),
('dog', 'Clumber Spaniel'),
('dog', 'Cocker Spaniel'),
('dog', 'Collie'),
('dog', 'Coton de Tulear'),
('dog', 'Curly-Coated Retriever'),
('dog', 'Czechoslovakian Vlcak'),
('dog', 'Dachshund'),
('dog', 'Dalmatian'),
('dog', 'Dandie Dinmont Terrier'),
('dog', 'Danish-Swedish Farmdog'),
('dog', 'Deutscher Wachtelhund'),
('dog', 'Doberman Pinscher'),
('dog', 'Dogo Argentino'),
('dog', 'Dogue de Bordeaux'),
('dog', 'Drentsche Patrijshond'),
('dog', 'Drever'),
('dog', 'Dutch Shepherd'),
('dog', 'English Cocker Spaniel'),
('dog', 'English Foxhound'),
('dog', 'English Setter'),
('dog', 'English Springer Spaniel'),
('dog', 'English Toy Spaniel'),
('dog', 'Entlebucher Mountain Dog'),
('dog', 'Estrela Mountain Dog'),
('dog', 'Eurasier'),
('dog', 'Field Spaniel'),
('dog', 'Finnish Lapphund'),
('dog', 'Finnish Spitz'),
('dog', 'Flat-Coated Retriever'),
('dog', 'French Bulldog'),
('dog', 'French Spaniel'),
('dog', 'German Longhaired Pointer'),
('dog', 'German Pinscher'),
('dog', 'German Shepherd Dog'),
('dog', 'German Shorthaired Pointer'),
('dog', 'German Spitz'),
('dog', 'German Wirehaired Pointer'),
('dog', 'Giant Schnauzer'),
('dog', 'Glen of Imaal Terrier'),
('dog', 'Golden Retriever'),
('dog', 'Gordon Setter'),
('dog', 'Grand Basset Griffon Vendéen'),
('dog', 'Great Dane'),
('dog', 'Great Pyrenees'),
('dog', 'Greater Swiss Mountain Dog'),
('dog', 'Greyhound'),
('dog', 'Hamiltonstovare'),
('dog', 'Hanoverian Scenthound'),
('dog', 'Harrier'),
('dog', 'Havanese'),
('dog', 'Hokkaido'),
('dog', 'Hovawart'),
('dog', 'Ibizan Hound'),
('dog', 'Icelandic Sheepdog'),
('dog', 'Irish Red and White Setter'),
('dog', 'Irish Setter'),
('dog', 'Irish Terrier'),
('dog', 'Irish Water Spaniel'),
('dog', 'Irish Wolfhound'),
('dog', 'Italian Greyhound'),
('dog', 'Jagdterrier'),
('dog', 'Japanese Akitainu'),
('dog', 'Japanese Chin'),
('dog', 'Japanese Spitz'),
('dog', 'Japanese Terrier'),
('dog', 'Jindo'),
('dog', 'Kai Ken'),
('dog', 'Karelian Bear Dog'),
('dog', 'Keeshond'),
('dog', 'Kerry Blue Terrier'),
('dog', 'Kishu Ken'),
('dog', 'Komondor'),
('dog', 'Kromfohrländer'),
('dog', 'Kuvasz'),
('dog', 'Labrador Retriever'),
('dog', 'Lagotto Romagnolo'),
('dog', 'Lakeland Terrier'),
('dog', 'Lancashire Heeler'),
('dog', 'Lapponian Herder'),
('dog', 'Leonberger'),
('dog', 'Lhasa Apso'),
('dog', 'Löwchen'),
('dog', 'Maltese'),
('dog', 'Manchester Terrier'),
('dog', 'Mastiff'),
('dog', 'Miniature American Shepherd'),
('dog', 'Miniature Bull Terrier'),
('dog', 'Miniature Pinscher'),
('dog', 'Miniature Schnauzer'),
('dog', 'Mountain Cur'),
('dog', 'Mudi'),
('dog', 'Neapolitan Mastiff'),
('dog', 'Nederlandse Kooikerhondje'),
('dog', 'Newfoundland'),
('dog', 'Norfolk Terrier'),
('dog', 'Norrbottenspets'),
('dog', 'Norwegian Buhund'),
('dog', 'Norwegian Elkhound'),
('dog', 'Norwegian Lundehund'),
('dog', 'Norwich Terrier'),
('dog', 'Nova Scotia Duck Tolling Retriever'),
('dog', 'Old English Sheepdog'),
('dog', 'Otterhound'),
('dog', 'Papillon'),
('dog', 'Parson Russell Terrier'),
('dog', 'Pekingese'),
('dog', 'Pembroke Welsh Corgi'),
('dog', 'Perro de Presa Canario'),
('dog', 'Peruvian Inca Orchid'),
('dog', 'Petit Basset Griffon Vendéen'),
('dog', 'Pharaoh Hound'),
('dog', 'Plott Hound'),
('dog', 'Pointer'),
('dog', 'Polish Lowland Sheepdog'),
('dog', 'Pomeranian'),
('dog', 'Poodle (Standard)'),
('dog', 'Poodle (Miniature)'),
('dog', 'Poodle (Toy)'),
('dog', 'Porcelaine'),
('dog', 'Portuguese Podengo'),
('dog', 'Portuguese Podengo Pequeno'),
('dog', 'Portuguese Pointer'),
('dog', 'Portuguese Sheepdog'),
('dog', 'Portuguese Water Dog'),
('dog', 'Pug'),
('dog', 'Puli'),
('dog', 'Pumi'),
('dog', 'Pyrenean Mastiff'),
('dog', 'Pyrenean Shepherd'),
('dog', 'Rafeiro do Alentejo'),
('dog', 'Rat Terrier'),
('dog', 'Redbone Coonhound'),
('dog', 'Rhodesian Ridgeback'),
('dog', 'Romanian Mioritic Shepherd Dog'),
('dog', 'Rottweiler'),
('dog', 'Russell Terrier'),
('dog', 'Russian Toy'),
('dog', 'Russian Tsvetnaya Bolonka'),
('dog', 'Saint Bernard'),
('dog', 'Saluki'),
('dog', 'Samoyed'),
('dog', 'Schapendoes'),
('dog', 'Schipperke'),
('dog', 'Scottish Deerhound'),
('dog', 'Scottish Terrier'),
('dog', 'Sealyham Terrier'),
('dog', 'Segugio Italiano'),
('dog', 'Shetland Sheepdog'),
('dog', 'Shiba Inu'),
('dog', 'Shih Tzu'),
('dog', 'Shikoku'),
('dog', 'Siberian Husky'),
('dog', 'Silky Terrier'),
('dog', 'Skye Terrier'),
('dog', 'Sloughi'),
('dog', 'Slovakian Wirehaired Pointer'),
('dog', 'Slovensky Cuvac'),
('dog', 'Slovensky Kopov'),
('dog', 'Small Munsterlander'),
('dog', 'Smooth Fox Terrier'),
('dog', 'Soft Coated Wheaten Terrier'),
('dog', 'Spanish Mastiff'),
('dog', 'Spanish Water Dog'),
('dog', 'Spinone Italiano'),
('dog', 'Stabyhoun'),
('dog', 'Staffordshire Bull Terrier'),
('dog', 'Standard Schnauzer'),
('dog', 'Sussex Spaniel'),
('dog', 'Swedish Lapphund'),
('dog', 'Swedish Vallhund'),
('dog', 'Taiwan Dog'),
('dog', 'Teddy Roosevelt Terrier'),
('dog', 'Thai Ridgeback'),
('dog', 'Tibetan Mastiff'),
('dog', 'Tibetan Spaniel'),
('dog', 'Tibetan Terrier'),
('dog', 'Tornjak'),
('dog', 'Tosa'),
('dog', 'Toy Fox Terrier'),
('dog', 'Transylvanian Hound'),
('dog', 'Treeing Tennessee Brindle'),
('dog', 'Treeing Walker Coonhound'),
('dog', 'Vizsla'),
('dog', 'Volpino Italiano'),
('dog', 'Weimaraner'),
('dog', 'Welsh Springer Spaniel'),
('dog', 'Welsh Terrier'),
('dog', 'West Highland White Terrier'),
('dog', 'Wetterhoun'),
('dog', 'Whippet'),
('dog', 'Wire Fox Terrier'),
('dog', 'Wirehaired Pointing Griffon'),
('dog', 'Wirehaired Vizsla'),
('dog', 'Working Kelpie'),
('dog', 'Xoloitzcuintli'),
('dog', 'Yakutian Laika'),
('dog', 'Yorkshire Terrier');

-- Insert Cat Breeds
INSERT INTO public.reference_breeds (species, name) VALUES
('cat', 'Abyssinian'),
('cat', 'Aegean'),
('cat', 'American Bobtail'),
('cat', 'American Curl'),
('cat', 'American Ringtail'),
('cat', 'American Shorthair'),
('cat', 'American Wirehair'),
('cat', 'Aphrodite Giant'),
('cat', 'Arabian Mau'),
('cat', 'Asian'),
('cat', 'Asian Semi-longhair'),
('cat', 'Australian Mist'),
('cat', 'Balinese'),
('cat', 'Bambino'),
('cat', 'Bengal'),
('cat', 'Birman'),
('cat', 'Bombay'),
('cat', 'Brazilian Shorthair'),
('cat', 'British Longhair'),
('cat', 'British Shorthair'),
('cat', 'Burmese'),
('cat', 'Burmilla'),
('cat', 'California Spangled'),
('cat', 'Chantilly-Tiffany'),
('cat', 'Chartreux'),
('cat', 'Chausie'),
('cat', 'Colorpoint Shorthair'),
('cat', 'Cornish Rex'),
('cat', 'Cymric'),
('cat', 'Cyprus'),
('cat', 'Devon Rex'),
('cat', 'Donskoy'),
('cat', 'Dragon Li'),
('cat', 'Dwelf'),
('cat', 'Egyptian Mau'),
('cat', 'European Shorthair'),
('cat', 'Exotic Shorthair'),
('cat', 'Foldex'),
('cat', 'German Rex'),
('cat', 'Havana Brown'),
('cat', 'Highlander'),
('cat', 'Himalayan'),
('cat', 'Japanese Bobtail'),
('cat', 'Javanese'),
('cat', 'Kanaani'),
('cat', 'Khao Manee'),
('cat', 'Kinkalow'),
('cat', 'Korat'),
('cat', 'Korean Bobtail'),
('cat', 'Korn Ja'),
('cat', 'Kurilian Bobtail'),
('cat', 'Lambkin'),
('cat', 'LaPerm'),
('cat', 'Lykoi'),
('cat', 'Maine Coon'),
('cat', 'Manx'),
('cat', 'Mekong Bobtail'),
('cat', 'Minskin'),
('cat', 'Minuet'),
('cat', 'Munchkin'),
('cat', 'Nebelung'),
('cat', 'Norwegian Forest Cat'),
('cat', 'Ocicat'),
('cat', 'Ojos Azules'),
('cat', 'Oregon Rex'),
('cat', 'Oriental Bicolor'),
('cat', 'Oriental Longhair'),
('cat', 'Oriental Shorthair'),
('cat', 'Persian (Modern)'),
('cat', 'Persian (Traditional)'),
('cat', 'Peterbald'),
('cat', 'Pixie-bob'),
('cat', 'Ragamuffin'),
('cat', 'Ragdoll'),
('cat', 'Raas'),
('cat', 'Russian Blue'),
('cat', 'Russian White, Black and Tabby'),
('cat', 'Sam Sawet'),
('cat', 'Savannah'),
('cat', 'Scottish Fold'),
('cat', 'Selkirk Rex'),
('cat', 'Serengeti'),
('cat', 'Serrade Petit'),
('cat', 'Siamese (Modern)'),
('cat', 'Siamese (Traditional)'),
('cat', 'Siberian'),
('cat', 'Singapura'),
('cat', 'Snowshoe'),
('cat', 'Sokoke'),
('cat', 'Somali'),
('cat', 'Sphynx'),
('cat', 'Suphalak'),
('cat', 'Thai'),
('cat', 'Thai Lilac'),
('cat', 'Tonkinese'),
('cat', 'Toyger'),
('cat', 'Turkish Angora'),
('cat', 'Turkish Van'),
('cat', 'Ukrainian Levkoy'),
('cat', 'York Chocolate'),
('cat', 'Domestic Short Hair'),
('cat', 'Domestic Medium Hair'),
('cat', 'Domestic Long Hair');
